export const defaultExcludedDomains = [
    "google.com",
    "yahoo.com",
    "bing.com",
    "duckduckgo.com",
    "keep.google.com",
    "docs.google.com",
    "calendar.google.com",
    "drive.google.com",
    "mail.google.com",
    "news.google.com",
    "mail.protonmail.com",
    "youtube.com",
    "news.ycombinator.com",
    "twitter.com",
    "linkedin.com",
    "reddit.com",
    "github.com",
    "stackoverflow.com",
    "developer.mozilla.org",
    "css-tricks.com",
    "twitch.tv",
    "amazon.com",
    "amazon.co.uk",
    "amazon.de",
    "ebay.com",
    "tailwindcss.com",
    "consent.yahoo.com",
    "messenger.com",
    "facebook.com",
    "scanofthemonth.com",
    "instagram.com",
    "pinterest.com",
    "netflix.com",
    "zoom.us",
    "tiktok.com",
    "discord.com",
    "microsoft.com",
    "imgur.com",
    "i.imgur.com",
    "producthunt.com",
    "awwwards.com",
    "figma.com",
    "Unsplash.com",
    "pudding.cool",
];

export const automaticallyEnabledFeatureFlag = "automatically-enabled";
export const allowlistDomainOnManualActivationFeatureFlag =
    "allowlist-domain-manual-activation";
export const collectAnonymousMetricsFeatureFlag = "collect-anonymous-metrics";
export const defaultFeatureFlags = {
    [automaticallyEnabledFeatureFlag]: false,
    [allowlistDomainOnManualActivationFeatureFlag]: true,
    [collectAnonymousMetricsFeatureFlag]: true,
};
