export const defaultExcludedDomains = [
    "google.com",
    "keep.google.com",
    "calendar.google.com",
    "drive.google.com",
    "mail.google.com",
    "mail.protonmail.com",
    "youtube.com",
    "news.ycombinator.com",
    "twitter.com",
    "linkedin.com",
    "reddit.com",
    "github.com",
    "stackoverflow.com",
    "developer.mozilla.org",
    "css-tricks.com",
    "twitch.tv",
    "amazon.de",
    "tailwindcss.com",
    "consent.yahoo.com",
    "messenger.com",
    "facebook.com",
    "scanofthemonth.com",
];
export const defaultAutomaticallyEnabled = true;
